- src: git+https://github.com/wikitops/ansible_epel
  version: "1.2"
  name: epel

- src: git+https://github.com/wikitops/ansible_java
  version: "1.1"
  name: java

- src: git+https://github.com/wikitops/ansible_zookeeper
  version: "1.2"
  name: zookeeper
