---

- name: VAULT GROUP | Create group
  group:
    name: "{{ vault_group }}"
    state: present

- name: VAULT USER | Create user
  user:
    name: "{{ vault_user }}"
    comment: "Vault user"
    group: "{{ vault_group }}"
    create_home: false
    system: true
